"""add_move_audit_log

Revision ID: 70043344a3d8
Revises: 001
Create Date: 2026-01-02 01:03:50.019477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70043344a3d8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_def_id', sa.UUID(), nullable=True),
    sa.Column('source_identity_hash', sa.String(), nullable=False),
    sa.Column('from_list_id', sa.String(), nullable=False),
    sa.Column('to_list_id', sa.String(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move_audit_log')
    # ### end Alembic commands ###
