"""add_scheduling_support

Revision ID: a8d319b57d44
Revises: 43c8c5615c06
Create Date: 2026-01-04 18:21:10.197875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8d319b57d44'
down_revision: Union[str, None] = '43c8c5615c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_periodic_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('crontab_minute', sa.String(), nullable=True),
    sa.Column('crontab_hour', sa.String(), nullable=True),
    sa.Column('crontab_day_of_week', sa.String(), nullable=True),
    sa.Column('crontab_day_of_month', sa.String(), nullable=True),
    sa.Column('crontab_month_of_year', sa.String(), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kwargs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_run_count', sa.Integer(), nullable=False),
    sa.Column('date_changed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_def_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['sync_def_id'], ['sync_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scheduled_sync_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_def_id', sa.UUID(), nullable=False),
    sa.Column('periodic_task_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('sync_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_def_id'], ['sync_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_def_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('alert_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sync_def_id'], ['sync_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Scheduling fields for sync_definitions
    op.add_column('sync_definitions', sa.Column('schedule_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sync_definitions', sa.Column('schedule_type', sa.String(), nullable=True))
    op.add_column('sync_definitions', sa.Column('schedule_interval_seconds', sa.Integer(), nullable=True))
    op.add_column('sync_definitions', sa.Column('schedule_cron_expression', sa.String(), nullable=True))
    op.add_column('sync_definitions', sa.Column('schedule_timezone', sa.String(), nullable=False, server_default='UTC'))
    op.add_column('sync_definitions', sa.Column('last_scheduled_run', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sync_definitions', sa.Column('next_scheduled_run', sa.DateTime(timezone=True), nullable=True))

    # Trigger tracking fields for sync_runs
    op.add_column('sync_runs', sa.Column('trigger_type', sa.String(), nullable=False, server_default='MANUAL'))
    op.add_column('sync_runs', sa.Column('celery_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove trigger tracking fields from sync_runs
    op.drop_column('sync_runs', 'celery_task_id')
    op.drop_column('sync_runs', 'trigger_type')

    # Remove scheduling fields from sync_definitions
    op.drop_column('sync_definitions', 'next_scheduled_run')
    op.drop_column('sync_definitions', 'last_scheduled_run')
    op.drop_column('sync_definitions', 'schedule_timezone')
    op.drop_column('sync_definitions', 'schedule_cron_expression')
    op.drop_column('sync_definitions', 'schedule_interval_seconds')
    op.drop_column('sync_definitions', 'schedule_type')
    op.drop_column('sync_definitions', 'schedule_enabled')

    # Drop new tables
    op.drop_table('sync_alerts')
    op.drop_table('scheduled_sync_audit')
    op.drop_table('celery_periodic_tasks')
    # ### end Alembic commands ###
